- name: setup MySQL
  hosts: deploy
  tasks:
  - name: remove /etc/mysql/mysql.conf.d/isucon.cnf
    become: true
    file:
      path: /etc/mysql/mysql.conf.d/isucon.cnf
      state: absent
      force: true
  - name: Restart MySQL
    service:
      name: mysql
      state: restarted
      enabled: yes
