- name: setup MySQL
  hosts: deploy
  tasks:
  - name: put /etc/mysql/mysql.conf.d/isucon.cnf
    become: true
    copy:
      src: isucon.cnf
      dest: /etc/mysql/mysql.conf.d/isucon.cnf
      force: yes
  - name: Restart MySQL
    become: true
    service:
      name: mysql
      state: restarted
      enabled: yes
  - name: Make log directory accessible from Rust
    become: true
    file:
      path: /var/log/mysql
      mode: '0755'
  - name: Make log file writable from Rust
    become: true
    file:
      path: /var/log/mysql/mysql-slow.log
      mode: '0666'
