" minimal vimrc
"
set nobackup noswapfile
set ambiwidth=single
set number ruler showcmd incsearch nohlsearch showmatch
set autoindent smartindent
set modeline modelines=2 history=50
set foldlevel=0 foldmethod=marker
set tabstop=4 shiftwidth=4 softtabstop=4 expandtab
set backspace=start,indent,eol
set wildmode=list:longest
set timeout ttimeoutlen=100
set mouse=a
set list listchars=tab:__,trail:-
set fillchars=vert:\ 
let mapleader="-"
set colorcolumn=100 synmaxcol=200
set undodir=~/.vim/undo undofile
set scrolloff=4
set completeopt=popup,menu
set fileencodings=utf8,euc-jp,sjis,cp932,default,latin1
set encoding=utf-8
set fileformats=unix
syntax on

cnoremap <c-p> <up>
cnoremap <c-n> <down>
nnoremap ! :!
nnoremap <silent><nowait> <c-t> :tabedit<cr>
nnoremap <silent><nowait> <c-p> :tabprevious<cr>
nnoremap <silent><nowait> <c-n> :tabnext<cr>
